//! Auto-typed query modules generated by `graphql_client::GraphQLQuery`.
//!
//! Each module corresponds to one `.graphql` file under
//! `src/subgraph/queries/`, and one entity in the vendored
//! `src/subgraph/schema.json`. The generated structs are intentionally
//! private to the crate — callers go through [`super::SubgraphClient`]
//! which converts them into the public typed structs in [`super::types`].

use graphql_client::GraphQLQuery;

/// The subgraph emits `BigInt` and `BigDecimal` as JSON strings; map them
/// to `String` and let our `From` adapters parse to `Decimal`.
#[allow(dead_code)]
pub type BigInt = String;
#[allow(dead_code)]
pub type BigDecimal = String;
#[allow(dead_code)]
pub type Bytes = String;

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "src/subgraph/schema.json",
    query_path = "src/subgraph/queries/get_pairs.graphql",
    response_derives = "Debug, Clone"
)]
pub struct GetPairs;

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "src/subgraph/schema.json",
    query_path = "src/subgraph/queries/get_pair_details.graphql",
    response_derives = "Debug, Clone"
)]
pub struct GetPairDetails;

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "src/subgraph/schema.json",
    query_path = "src/subgraph/queries/get_liq_margin_threshold.graphql",
    response_derives = "Debug, Clone"
)]
pub struct GetLiqMarginThreshold;

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "src/subgraph/schema.json",
    query_path = "src/subgraph/queries/get_open_trades.graphql",
    response_derives = "Debug, Clone"
)]
pub struct GetOpenTrades;

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "src/subgraph/schema.json",
    query_path = "src/subgraph/queries/get_orders.graphql",
    response_derives = "Debug, Clone"
)]
pub struct GetOrders;

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "src/subgraph/schema.json",
    query_path = "src/subgraph/queries/get_recent_history.graphql",
    response_derives = "Debug, Clone"
)]
pub struct GetRecentHistory;

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "src/subgraph/schema.json",
    query_path = "src/subgraph/queries/get_order_by_id.graphql",
    response_derives = "Debug, Clone"
)]
pub struct GetOrderById;

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "src/subgraph/schema.json",
    query_path = "src/subgraph/queries/get_trade_by_id.graphql",
    response_derives = "Debug, Clone"
)]
pub struct GetTradeById;
